export const AUTH_CHECK_STATE = 'AUTH_CHECK_STATE';
export const AUTH_USER = 'AUTH_USER';
export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_CHECK_TIMEOUT = 'AUTH_CHECK_TIMEOUT';
export const AUTH_INITIATE_LOGOUT = 'AUTH_INITIATE_LOGOUT';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';

export const GET_CHATS = 'GET_CHATS';
export const GET_CHATS_START = 'GET_CHATS_START';
export const GET_CHATS_SUCCESS = 'GET_CHATS_SUCCESS';

export const JOIN_CHAT = 'JOIN_CHAT';
export const JOIN_CHAT_START = 'JOIN_CHAT_START';
export const JOIN_CHAT_SUCCESS = 'JOIN_CHAT_SUCCESS';

export const LEAVE_CHAT = 'LEAVE_CHAT';
export const LEAVE_CHAT_START = 'LEAVE_CHAT_START';
export const LEAVE_CHAT_SUCCESS = 'LEAVE_CHAT_SUCCESS';

export const DELETE_CHAT = 'DELETE_CHAT';

export const SET_ACTIVE_CHAT = 'SET_ACTIVE_CHAT';

export const GET_CHAT_MESSAGES = 'GET_CHAT_MESSAGES';
export const GET_CHAT_MESSAGES_START = 'GET_CHAT_MESSAGES_START';
export const GET_CHAT_MESSAGES_SUCCESS = 'GET_CHAT_MESSAGES_SUCCESS';

export const ADD_MESSAGE = 'ADD_MESSAGE';
export const ADD_MESSAGE_START = 'ADD_MESSAGE_START';
export const ADD_MESSAGE_SUCCESS = 'ADD_MESSAGE_SUCCESS';

export const SET_AUTH_REDIRECT_PATH = 'SET_AUTH_REDIRECT_PATH';
